# Generated by Django 4.1 on 2022-08-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('numberOfEmployees', models.IntegerField()),
                ('sector', models.TextField()),
                ('isTech', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyNumberOfEmployees', models.IntegerField()),
                ('companySector', models.TextField()),
                ('isTechCompany', models.BooleanField()),
                ('birthDate', models.DateField()),
                ('gender', models.TextField()),
                ('hasFamiliarHistory', models.BooleanField()),
                ('hasEmployeeHistory', models.BooleanField()),
                ('hasHealthcareCoverage', models.BooleanField()),
                ('hasBenefits', models.BooleanField()),
                ('wasDiagnosed', models.BooleanField()),
            ],
        ),
    ]
