# Generated by Django 4.1 on 2022-08-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhti', '0002_company_employeeanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeanswer',
            name='birthDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeanswer',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeanswer',
            name='hasBenefits',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeanswer',
            name='hasEmployeeHistory',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeanswer',
            name='hasFamiliarHistory',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeanswer',
            name='hasHealthcareCoverage',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='employeeanswer',
            name='wasDiagnosed',
            field=models.BooleanField(null=True),
        ),
    ]
