# Generated by Django 4.1 on 2022-08-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhti', '0003_alter_employeeanswer_birthdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeanswer',
            name='companyNumberOfEmployees',
        ),
        migrations.RemoveField(
            model_name='employeeanswer',
            name='companySector',
        ),
        migrations.RemoveField(
            model_name='employeeanswer',
            name='isTechCompany',
        ),
        migrations.AddField(
            model_name='employeeanswer',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mhti.company'),
        ),
    ]
