# Generated by Django 4.1 on 2022-08-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhti', '0004_remove_employeeanswer_companynumberofemployees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeanswer',
            old_name='hasFamiliarHistory',
            new_name='hasFamilyHistory',
        ),
        migrations.RemoveField(
            model_name='employeeanswer',
            name='company',
        ),
        migrations.AddField(
            model_name='employeeanswer',
            name='companyId',
            field=models.IntegerField(null=True),
        ),
    ]
